# 서버 포트 번호
server:
  port: 80
  
spring:
  # 콘솔 ANSI 색상
  output:
    ansi:
      enabled: always
  
  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/
  
  # spring-jdbc 설정시 아래 정보 없으면 가동시 에러 발생
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

  # security
  security:
    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 311773755012-bn9o90372kqccsvecsi68ofpejd1tr44.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 271345425372998
            client-secret: 5e266676e0d37b8e12bc76237b086f6c
            scope:
              - email
              - public_profile
          naver:
            client-id: WDl1M3k7K9zWA4BUno0n
            client-secret: qrlQRYVheo
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8091/login/oauth2/code/naver  # google, facebook 과 달리 naver 는 제공해줘야 함

        # provider 로 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json 으로 받아올때 response 라는 name값으로 보내줌.

# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  
# 각종 설정값들을 임의로 설정한뒤 @Value 로 설정값을 주입받아 사용 가능
app:
  # 파일 업로드 경로
  upload:
    path: upload

  # 페이징 관련 세팅값
  pagination:
    write_pages: 10  # 기본 write_pages 값. 한 [페이징] 당 몇개의 페이지가 표시되나
    page_rows: 10    # 기본 page_rows 값.  한 '페이지'에 몇개의 글을 리스트 할것인가?
    

  # Google 로그인 관련 세팅값
#  google:
#    redirect_uri: /oauth2/authorization/google  # OAuth2 client 를 사용할경우 고정값임

#  facebook:
#    redirect_uri: /oauth2/authorization/google  # OAuth2 client 를 사용할경우 고정값임

  # OAuth2
  oauth2:
    password: 1234  # 보안주의!

    # Kakao 로그인 관련 세팅값
    kakao:
      client-id: 461a0dcad35a85bb53c0e1a61e854049   # 앱 키
      redirect-uri: http://localhost:8091/oauth2/kakao/callback  # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token # access token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me # 사용자 profile 요청 URI







